In [14]:
import duckdb
import pandas as pd
from pathlib import Path
# ---- from PKL ----
df = pd.read_pickle("../data/clean_job_step1.pkl")

df.head()

,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,...,postedCompany_name,salary_maximum,salary_minimum,status_jobStatus,title,average_salary,category_names,is_hybrid,category_1,category_2
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,...,WORKSTONE PTE. LTD.,2800,2000,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,"[Environment / Health, Manufacturing, Sciences...",True,Environment / Health,Manufacturing
1,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,...,TRUST RECRUIT PTE. LTD.,5500,4000,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,[Information Technology],False,Information Technology,NaN
2,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,...,PU TIEN SERVICES PTE. LTD.,4600,3800,Closed,Senior Technician,4200.0,[Repair and Maintenance],False,Repair and Maintenance,NaN
3,Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,...,TRUST RECRUIT PTE. LTD.,10000,5000,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,[Information Technology],False,Information Technology,NaN
4,Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,...,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Closed,Sales / Admin Cordinator,2900.0,[Admin / Secretarial],False,Admin / Secretarial,NaN

In [13]:
# Numeric: salaries, experience, applications
df[["salary_minimum", "salary_maximum", "average_salary",
    "minimumYearsExperience", "metadata_totalNumberJobApplication",
    "metadata_totalNumberOfView", "numberOfVacancies", "category_1","category_2"]].describe()

,salary_minimum,salary_maximum,average_salary,minimumYearsExperience,metadata_totalNumberJobApplication,metadata_totalNumberOfView,numberOfVacancies
count,1.012928e+06,1.012928e+06,1.012928e+06,1.012928e+06,1.012928e+06,1.012928e+06,1.012928e+06
mean,3.751730e+03,5.449035e+03,4.600383e+03,2.774770e+00,2.101954e+00,2.638672e+01,2.643842e+00
std,2.070168e+03,3.183382e+03,2.579314e+03,2.443127e+00,1.020707e+01,8.033257e+01,1.032836e+01
min,6.000000e+02,6.100000e+02,6.050000e+02,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.500000e+03,3.500000e+03,3.000000e+03,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
50%,3.000000e+03,4.500000e+03,3.850000e+03,2.000000e+00,0.000000e+00,4.000000e+00,1.000000e+00
75%,4.500000e+03,6.500000e+03,5.500000e+03,4.000000e+00,1.000000e+00,1.700000e+01,2.000000e+00
max,1.999900e+04,2.000000e+04,1.999950e+04,3.000000e+01,1.342000e+03,8.190000e+03,9.990000e+02

In [ ]:

# Categorical: who/what
for c in ["employmentTypes", "positionLevels", "status_jobStatus", "category_1", "category_2"]:
    print(f"\n{c}")
    print(df[c].value_counts(normalize=True).head(10) * 100)

employmentTypes
employmentTypes
Permanent                44.384793
Full Time                37.983154
Contract                 13.269650
Part Time                 2.021565
Temporary                 1.616304
Internship/Attachment     0.483253
Freelance                 0.150652
Flexi-work                0.090628
Name: proportion, dtype: float64

positionLevels
positionLevels
Executive            24.713800
Junior Executive     16.274701
Non-executive        12.516092
Fresh/entry level    10.870170
Professional         10.671538
Manager              10.616648
Senior Executive      9.785296
Middle Management     2.554871
Senior Management     1.996884
Name: proportion, dtype: float64

status_jobStatus
status_jobStatus
Open       86.390543
Closed     11.481665
Re-open     2.127792
Name: proportion, dtype: float64

category_1
category_1
Admin / Secretarial                 9.766439
Engineering                         9.741759
Information Technology              9.622007
Accounting / Auditing / Taxation    7.595703
Building and Construction           7.245135
Customer Service                    6.154238
F&B                                 5.719952
Banking and Finance                 4.311659
Logistics / Supply Chain            4.304847
Sales / Retail                      3.527497
Name: proportion, dtype: float64

category_2
category_2
Others                         9.957723
Customer Service               9.465994
Sales / Retail                 7.392855
Information Technology         7.263383
Engineering                    7.134704
Manufacturing                  5.832056
Admin / Secretarial            3.941764
Logistics / Supply Chain       3.872800
Healthcare / Pharmaceutical    3.297839
Human Resources                3.208529
Name: proportion, dtype: float64

In [12]:
df.head()

,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,...,salary_maximum,salary_minimum,status_jobStatus,title,average_salary,category_names,n_categories,is_hybrid,category_1,category_2
0,Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,0,...,2800,2000,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0,"[Environment / Health, Manufacturing, Sciences...",3,True,Environment / Health,Manufacturing
1,Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,2,...,5500,4000,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0,[Information Technology],1,False,Information Technology,NaN
2,Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,3,...,4600,3800,Closed,Senior Technician,4200.0,[Repair and Maintenance],1,False,Repair and Maintenance,NaN
3,Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,8,...,10000,5000,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0,[Information Technology],1,False,Information Technology,NaN
4,Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,2,...,3400,2400,Closed,Sales / Admin Cordinator,2900.0,[Admin / Secretarial],1,False,Admin / Secretarial,NaN